# Changes here will be overwritten by Copier
_commit: 22b3cb1
_src_path: gh:maxlansky1/projectTemplate
author_email: dick@gmail.com
author_name: Иванушка дурачок
project_name: yaro_tg_bot
project_summary: Телеграм бот для отслеживания подписок и отписок в телеграм канал
