name: Автодеплой

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    environment: vps_deploy
    steps:

      - name: Проверка репозитория
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Проверяем, подтягиваются ли переменные
        run: |
          echo "🔍 DEBUG OUTPUT:"
          echo "SSH_HOST:       ${{ secrets.SSH_HOST }}"
          echo "SSH_USER:       ${{ secrets.SSH_USER }}"
          echo "SSH_PORT:       ${{ secrets.SSH_PORT }}"
          echo "SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}"
          echo "DEPLOY_PATH:    ${{ secrets.DEPLOY_PATH }}"
          echo "TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}"
          echo "REPO_NAME:      ${{ github.repository }}"
          echo "COMMIT_SHA:     ${{ github.sha }}"

          # Проверка, не пустые ли ключевые переменные
          if [[ -z "${{ secrets.SSH_HOST }}" ]]; then echo "❌ SSH_HOST is empty"; fi
          if [[ -z "${{ secrets.SSH_USER }}" ]]; then echo "❌ SSH_USER is empty"; fi
          if [[ -z "${{ secrets.SSH_PORT }}" ]]; then echo "❌ SSH_PORT is empty"; fi
          if [[ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]]; then echo "❌ SSH_PRIVATE_KEY is empty"; fi
          if [[ -z "${{ secrets.DEPLOY_PATH }}" ]]; then echo "❌ DEPLOY_PATH is empty"; fi

      - name: Определяем тип изменений и выбираем пересборку/рестарт
        id: changes
        run: |
          # Проверка, не первый ли это коммит
          if [[ "${{ github.event.before }}" != "0000000000000000000000000000000000000000" ]]; then
            # Получаем измененные файлы между коммитами
            changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
            echo "$changed_files"
          else
            echo "Первый коммит — требуется полная пересборка"
            echo "run_rebuild=true" >> $GITHUB_ENV
            exit 0
          fi

          # Проверка на изменения в Dockerfile, docker-compose или requirements.txt
          if echo "$changed_files" | grep -qE '(Dockerfile|docker-compose.*\.yml|requirements\.txt)'; then
            echo "run_rebuild=true" >> $GITHUB_ENV
            echo "action_type=Пересборка" >> $GITHUB_ENV
          else
            echo "run_rebuild=false" >> $GITHUB_ENV
            echo "action_type=Рестарт" >> $GITHUB_ENV
          fi

      - name: Определяем название репозитория
        run: |
          echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: Подключаемся по SSH
        id: ssh-connect
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Переходим в директорию проекта 
            cd "${{ secrets.DEPLOY_PATH }}/${{ env.REPO_NAME }}"
            
            # Полностью откатываем любые локальные изменения
            git reset --hard

            # Настройка git для автоматического слияния
            git config pull.rebase false

            # Подтягиваем изменения из main
            git pull

            # Выполняем нужное действие в зависимости от изменений
            if [ "${{ env.run_rebuild }}" = "true" ]; then
              echo "🔄 Выполняем полный rebuild..."
              make rebuild
            else
              echo "🔁 Перезапускаем сервис без пересборки..."
              make restart
            fi

            # Получаем список контейнеров
            docker ps -a

      - name: Отправляем сообщение в телеграм бота
        if: success()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          REPO_NAME: ${{ github.repository }}
          COMMIT_SHA: ${{ github.sha }}
          CONTAINERS: ${{ steps.ssh-connect.outputs.stdout }}
          ACTION_TYPE: ${{ env.action_type }}

        run: |
          # Формируем сообщение
          MESSAGE="✅ <b>${action_type}</b>

          📦 <b>Repo:</b> <code>${REPO_NAME}</code>
          📌 <b>Commit:</b> <a href='https://github.com/${REPO_NAME}/commit/${COMMIT_SHA}'>${COMMIT_SHA:0:7}</a>
          🕒 <b>Time:</b> $(date '+%Y-%m-%d %H:%M:%S')

          📋 <b>Запущенные контейнеры:</b>
          <pre>${CONTAINERS}</pre>

          🔗 <a href='https://github.com/${REPO_NAME}/actions/runs/${GITHUB_RUN_ID}'>View in GitHub Actions</a>"

          # Отправляем сообщение через бота
          curl -s -X POST \
            "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d parse_mode="HTML" \
            --data-urlencode text="$MESSAGE"